Add official eslint plugin for hooks
CheesecakeLabs/eslint-config-cheesecakelabs pull request #10
Opened 2019-04-08 12:25 UTC by matbueno

The React team has set the Rules of Hook: 

1. Only call hooks at the top level;
2. Only call hooks on react functions.

They added constrictions to enforce this in a eslint plugin, so I added it as recommended by the package to Cheesecake Labs' default linter.

The page discussing this can be found [here](https://reactjs.org/docs/hooks-rules.html).
The package is [here](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks).

2019-04-08 12:34 UTC, helderberto submitted a review, later dismissed
Great job! 💯

2019-04-10 18:35 UTC, dleitee requested changes
I liked the idea to put this plugin, but you put it on the wrong file. There is a file called react.js where we add all stuff related to react, could you move this config to there?

2019-04-10 19:35 UTC, matbueno commented
> I liked the idea to put this plugin, but you put it on the wrong file. There is a file called react.js where we add all stuff related to react, could you move this config to there?

Fixed it

2019-04-10 19:57 UTC, helderberto approved these changes

2019-04-11 12:54 UTC, dleitee approved these changes

2019-04-12 18:04 UTC, merged